### ISSUE TITLE
每个项目的基础设施层都需要创建一个实体类实现IModuleInitializer这个接口，实体类中需要手动的 services.AddScoped，项目大的话，每个ModuleInitializer中会有很多的services.AddScoped（），这样会很方便？

### ISSUE THREAD

**Issue by liuyongfei813** [yangzhongke/NETBookMaterials#11]
杨老师，我把builder.ConfigureExtraServices（）和 services.RunModuleInitializers(assemblies);这两个方法，都改造成可以根据外部传入的不同的接口，实现DI的自动注入，每个项目在创建ModuleInitializer实现类基础上，也可以根据传入外部参数的接口类型集合，实现框架的自动注入。下面是我实现的代码，我现在不清楚这样实现有没有性能上的损失，这样改造不知道是否合适？
builder.ConfigureExtraServices(new InitializerOptions
{
    EventBusQueueName = "IdentityService.WebAPI",
    LogFilePath = "D:/temp/IdentityService.log"
}, options =>
{
    options.Add(typeof(IServiceSupport));
});

 //获取所有的类库
  var assemblies = ReflectionHelper.GetAllReferencedAssemblies();
  //调整为可以根据前端传递需要注入的接口集合
  services.RunModuleInitializers(assemblies, options);
// <summary>
		/// 每个项目中都可以自己写一些实现了IModuleInitializer接口的类，
		/// 在其中注册自己需要的服务，这样避免所有内容到入口项目中注册
		/// todo:后续需要改造成所有的实现某些接口的类也直接注入框架
		/// </summary>
		/// <param name="services"></param>
		/// <param name="assemblies"></param>
		public static IServiceCollection RunModuleInitializers(this IServiceCollection services,
		 IEnumerable<Assembly> assemblies,Action<IocOption> option)
		{
			foreach(var asm in assemblies)
            {
				Type[] types = asm.GetTypes();
				var moduleInitializerTypes = types.Where(t => !t.IsAbstract && typeof(IModuleInitializer).IsAssignableFrom(t));
				foreach(var implType in moduleInitializerTypes)
                {
					//通过反射生成实体类，并执行内部的方法
					var initializer = (IModuleInitializer?)Activator.CreateInstance(implType);
					if (initializer == null)
					{
						throw new ApplicationException($"Cannot create ${implType}");
					}
					initializer.Initialize(services);
				}  
			}

            //liuyongfei 2023年1月10日15:14:10 后续添加可以根据不同类型接口实现DI自动注入
            if (option != null)
            {
                var iocOption = new IocOption();
                option(iocOption);//客户端类型注入 
                var definedTypes = assemblies.SelectMany(y => y.DefinedTypes).ToList();
                foreach (var type in iocOption.Types)
                {
                    var allTypes = definedTypes.Where(t => type.GetTypeInfo().IsAssignableFrom(t.AsType()));

                    var abstractTypes = allTypes.Where(t => t.IsInterface || t.IsAbstract);
                    var implTypes = allTypes.Where(t => t.IsInterface == false && t.IsAbstract == false).ToList();

                    foreach (var abstractType in abstractTypes)
                    {
                        if (abstractTypes.Count() > 1
                            && abstractType.AssemblyQualifiedName == type.AssemblyQualifiedName)
                        {
                            continue;
                        }
                        var _implTypes = implTypes.Where(t => t.ImplementedInterfaces.Any(impl => impl.AssemblyQualifiedName == abstractType.AssemblyQualifiedName)
                                    || t.BaseType?.AssemblyQualifiedName == abstractType.AssemblyQualifiedName);
                        foreach (var implClass in _implTypes)
                        {
                            if (iocOption.ExceptTypes.Count > 0)
                            {
                                if (iocOption.ExceptTypes.Where(
                                    t => t.AssemblyQualifiedName == abstractType.AssemblyQualifiedName
                                    || t.AssemblyQualifiedName == implClass.AssemblyQualifiedName).Any())
                                {
                                    continue;
                                }
                            }
                            //配置ScopedDI
                            services.AddScoped(abstractType, implClass);
                        }
                    }
                }
            }
         
            return services;
}

**Comment by yangzhongke** [comment]
已经微信回复
