### ISSUE TITLE
Bug:Zack.EventBus包的使用中出现问题

### ISSUE THREAD

**Issue by pengwei-v2** [yangzhongke/NETBookMaterials#13]
我有两个微服务A和B，A是生产者也是自己的消费者，B是消费者，当我先启动B再启动A时，A发出的事件A自己不能监听到，B可以监听到；当我先启动A再启动B时，A自己发出的事件A自己可以监听到，B不能监听到

**Comment by yangzhongke** [comment]
我这个只是教学用演示原理的，并不完善。你可以根据你的需要进行完善，比如搞一个消息发布者和订阅者关系的配置文件，在发布者启动的时候就把订阅者先注册上，这样就可以解决这个问题了。
