### ISSUE TITLE
重写BaseDbContext.SaveChangesAsync的问题?

### ISSUE THREAD

**Issue by zrq-github** [yangzhongke/NETBookMaterials#14]
文件路径。最后大项目代码/YouZack-VNext/Zack.Infrastructure/EFCore/BaseDbContext.cs
为什么要将领域事件的发布，放在 base.SaveChangesAsync() 之前？
如果 base.SaveChangesAsync() 抛出异常，应该不能发布领域事件吧？

**Comment by yangzhongke** [comment]
这样领域事件的消费者中的数据库操作就会和这里的操作在同一个事务中了。
