### ISSUE TITLE
切换至MySql遇到的问题总结

### ISSUE THREAD

**Issue by zoulei0718** [yangzhongke/NETBookMaterials#2]
下载代码后，因为电脑只安装了MySql，没安装SqlServer，所以就想用MySql做数据库，没想到遇到不少问题，现在总结一下，最后还有个问题：

1. 修改数据库配置源，用MySqlConnection代替SqlConnection（安装程序集MySql.Data和Pomelo.EntityFrameworkCore.MySql），WebApplicationBuilderExtensions.ConfigureDbConfiguration()方法里，我指定了配置表表名为小写（有些MySql云数据库对表名大小写敏感，如果不改MySql的配置，会导致Win上开发没问题，一上线就出问题）
   `configBuilder.AddDbConfiguration(() => new MySqlConnection(connStr), reloadOnChange: true, reloadInterval: TimeSpan.FromSeconds(5), tableName: "t_configs");`
2. 注册所有DbContext的方法里也修改一下，WebApplicationBuilderExtensions.ConfigureExtraServices()里的`services.AddAllDbContexts()`里的`//ctx.UseSqlServer(connStr); ctx.UseMySql(connStr, ServerVersion.AutoDetect(connStr));`
3. 转码和认证项目接口，是通过设计时工厂（IDesignTimeDbContextFactory）创建DbContext的，所以还得修改DbContextOptionsBuilderFactory里得Create()方法，`//optionsBuilder.UseSqlServer(connStr); optionsBuilder.UseMySql(connStr, ServerVersion.AutoDetect(connStr));`
4. 在MySql里新建数据库与环境变量里数据库连接字符串保持一致的数据库名称；
5. 在新建的数据库里新建表：t_configs，尤其要新建Redis的配置且启动Redis服务，否则数据库迁移时，因为Redis连接失败，导致迁移失败，启动所有项目前，还需按PPT新增Cors、RabbitMQ、JWT、FileService:SMB、ElasticSearch等及其值；
6. 删除所有源码里已生成的Migrations文件夹，重新生成迁移目录及文件；
7. 逐个项目迁移数据库（设置WebApi为启动项，Add-Migration，Update-Database）;
8. 数据库迁移完成后，最后我的数据库里共有14张表（含__efmigrationshistory）；
**9. WebApplicationBuilderExtensions.cs文件里的ConfigureExtraServices()方法里的`builder.Services.AddAuthentication();`是不是多余的，因为下面有`builder.Services.AddJWTAuthentication(jwtOpt);`了，认证服务重复了？**

**Comment by yangzhongke** [comment]
谢谢分享。
不重复，AddAuthentication是认证的基础服务，AddJWTAuthentication是基于他的，因为还有其他类型的AddXXXAuthentication。其次，一般重复注册服务也不会报错。

**Comment by qinweizhi** [comment]
感谢，我对照了一下改成mysql，确实差不多一样的。

**Comment by yangzhongke** [comment]
其他问题就要你自己研究了，我没精力，抱歉。
