### ISSUE TITLE
Zack.AspNetCore包中的IDistributedCacheHelper中的GetOrCreateAsync方法存取字符串出现问题

### ISSUE THREAD

**Issue by hardstyleWyl** [yangzhongke/NETBookMaterials#4]
当我用这个方法存取字符串时它自动给我加了\" ,看了源码是使用了System.Text.Json.JsonSerializer.Serialize方法导致的

**Comment by yangzhongke** [comment]
这不是Bug，就是这样设计的。
因为存的对象可能是各种类型，所以我把对象序列化为Json类型保存，读取的时候会再反序列化。
