### ISSUE TITLE
最后大项目代码里的Zack.DomainCommons/Models/BaseEntity.cs 里的private List<INotification> domainEvents = new();是否应该使用static修饰

### ISSUE THREAD

**Issue by znhisme** [yangzhongke/NETBookMaterials#9]
今天学习该项目的时候发现，实体添加了领域事件，然后并没有自动触发该事件。
调试过程中发现Zack.DomainCommons/Models/BaseEntity.cs 里面的 private List<INotification> domainEvents = new();确实能够添加成功，
但是在YouZack-VNext/Zack.Infrastructure/EFCore/MediatorExtensions.cs中的 ：
                     var domainEvents = domainEntities
                    .SelectMany(x => x.Entity.GetDomainEvents())
                    .ToList();
里拿不到值。
经过测试，在private List<INotification> domainEvents = new()上加了个static拿到值了。

**Comment by yangzhongke** [comment]
应该是你用错了，把DbContext的生命周期设置为了瞬态，导致每次获取的都是一个新的DbContext，你应该设置为Scoped。
